#!/bin/bash
for i in $@; do
	if [ ! -f ${i} ]; then
		continue
	fi

	flex -o `echo ${i} | sed -e 's,l$,lex.cpp,g'` \
			--header-file=`echo ${i} | sed -e 's,l$,lex.hpp,g'` \
			${i} 
	
	if [ ! $? == 0 ]; then
		echo failed to generate lex files;
		exit 1
	fi
done
